---

- name: "Exportarr: Create exportarr_prowlarr container"
  community.docker.docker_container:
    docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
    name: exportarr_prowlarr
    image: "{{ exportarr_container_image }}"
    pull: yes
    ports:
      - "{{ prowlarr_exportarr_port }}:{{ prowlarr_exportarr_port }}"
    env:
      PUID: "{{ user_puid }}"
      PGID: "{{ group_pgid }}"
      TZ: "{{ default_timezone }}"
      UMASK: "022"
      PORT: "{{ prowlarr_exportarr_port }}"
      URL: "http://{{ ansible_default_ipv4.address }}:{{ prowlarr_port }}"
      APIKEY: "{{ prowlarr_api_key }}"
    command: ["prowlarr"]
    state: started
    restart_policy: unless-stopped
