---
# defaults file for hdhomerun
hdhomerun_container_image: "timstephens24/hdhomerun_dvr:latest"

user_puid: "1000"
group_pgid: "100"
default_timezone: "America/New_York"
container_directory_root: /volume1/docker
