---

- name: Restart Docker
  command:
    # Command Changed from DSM6 to DSM7
    #cmd: /usr/syno/sbin/synoservice --restart pkgctl-Docker
    cmd: /usr/syno/bin/synosystemctl restart pkgctl-Docker

- name: Load Tun Driver
  command:
    cmd: insmod /usr/lib/modules/tun.ko
