---

# Mylar
mylar_container_image: "lscr.io/linuxserver/mylar3:latest"

user_puid: "1000"
group_pgid: "100"
default_timezone: "America/New_York"
container_directory_root: /volume1/docker
synology_htpc_stack_enable: false
