---

- name: Check for gluetun directory
  ansible.builtin.stat:
    path: "{{ container_directory_root }}/gluetun"
  register: _gluetun_config_dir
  tags:
    - gluetun

- name: Check for tun device
  ansible.builtin.stat:
    path: "/dev/net/tun"
  register: _tun_device
  tags:
    - gluetun

- name: "Create directories to house gluetun data"
  ansible.builtin.file:
    path: "{{ container_directory_root }}/gluetun"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: "0775"
    recurse: true
  register: _gluetun_config_dir
  tags:
    - gluetun
  when:
    - _gluetun_config_dir is defined
    - not _gluetun_config_dir.stat.exists

- name: Check if gluetun is running
  tags:
    - gluetun
  register: _gluetun_state
  community.docker.docker_container_info:
    docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
    name: gluetun

- name: Set Gluetun facts
  tags:
    - gluetun
  ansible.builtin.set_fact:
    gluetun_config_dir: "{{ _gluetun_config_dir }}"
    gluetun_state: "{{ _gluetun_state }}"
    tun_device: "{{ _tun_device }}"

- name: Tun Driver
  when: not _tun_device.stat.exists
  block:
    - name: Add script to start tun driver automatically on Synology
      register: _gluetun_driver
      ansible.builtin.template:
        src: start_tun.sh.j2
        dest: /usr/local/etc/rc.d/start_tun.sh
        owner: "root"
        group: "root"
        mode: "0770"
    - name: Load Tun Driver Manually as notify doesn't work.
      ansible.builtin.command:
        cmd: insmod /usr/lib/modules/tun.ko
      register: _gluetun_driver_manual_loading
      changed_when: true
    - name: "Gluetun: print gluetun driver"
      ansible.builtin.debug:
        msg: "{{ _gluetun_driver }}"
    - name: Driver manual loading output
      ansible.builtin.debug:
        msg: "{{ _gluetun_driver_manual_loading }}"
    - name: Gluetun Driver Loaded
      ansible.builtin.set_fact:
        # gluetun_is_running: "{{ _gluetun_status.ansible_facts.docker_container.State.Running }}"
        # gluetun_is_running: "{{ _gluetun_status.docker_container.State.Running }}"
        gluetun_driver: "{{ _gluetun_driver }}"
    - name: Gluetun Driver Manually Loaded
      ansible.builtin.set_fact:
        gluetun_driver_manual_loading: "{{ _gluetun_driver_manual_loading }}"
    - name: "Gluetun: print gluetun_driver"
      ansible.builtin.debug:
        msg: "{{ gluetun_driver }}"
    - name: Output driver manual loading
      ansible.builtin.debug:
        msg: "{{ gluetun_driver_manual_loading }}"
# end block

- name: Launch GLuetun
  when: not _gluetun_state.exists
  tags:
    - gluetun
  block:
    - name: Launch GlueTun VPN Container
      register: _gluetun_status
      community.docker.docker_container:
        docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
        name: gluetun
        image: "qmcgaw/gluetun:{{ gluetun_container_version }}"
        networks:
          - name: synology-docker-network
        capabilities:
          - NET_ADMIN
        network_mode: bridge
        tty: true
        detach: true
        pull: true
        retries: 5
        delay: 30
        volumes:
          - "{{ container_directory_root }}/gluetun:/gluetun"
          - "/dev/net/tun:/dev/net/tun"
        env:
          VPN_SERVICE_PROVIDER: "{{ gluetun_vpn_service_provider }}"
          VPN_TYPE: "{{ gluetun_vpn_type }}"
          OPENVPN_USER: "{{ gluetun_openvpn_user }}"
          OPENVPN_PASSWORD: "{{ gluetun_openvpn_password }}"
          SERVER_REGIONS: "{{ gluetun_openvpn_regions }}"
          FIREWALL_OUTBOUND_SUBNETS: "{{ gluetun_firewall_outbound_subnets }}"
    #     PIA_ENCRYPTION: "normal"
    #     OPENVPN_CIPHER: "BF-CBC"
        ports:
          - "8888:8888/tcp"
          - "8388:8388/tcp"
          - "8388:8388/udp"
          # Deluge
          - "8112:8112"
          # NzbGet
          - "6789:6789"
          # NzbHydra2
          - "5076:5076"
          # Swag
          - "5080:80"
          - "5443:443"
          # Jackett
          - "9117:9117"
          # Bazarr
          - "6767:6767"
          # Sonarr
          - "8989:8989"
          # Homarr
          - "7575:7575"
          # Radarr
          - "7878:7878"
          # Couchpotato
          - "5050:5050"
          # Mylar
          - "8090:8090"
          # Sabnzbd
          - "8080:8080"
          # Lidarr
          - "8686:8686"
          # Readarr
          - "8787:8787"
          # headphones
          - "8181:8181"
          # tvheadend
          # - "9981:9981"
          # - "9982:9982"
          # Prowlarr
          - "9696:9696"
          # Threadfin
          - "34400:34400"
          - "{{ gluetun_control_port }}:8000/tcp"
        restart_policy: always
        state: started

    - name: "Gluetun: print gluetun_status"
      ansible.builtin.debug:
        msg: "{{ _gluetun_status }}"
    - name: Gluetun is Running
      ansible.builtin.set_fact:
        # gluetun_is_running: "{{ _gluetun_status.ansible_facts.docker_container.State.Running }}"
        # gluetun_is_running: "{{ _gluetun_status.docker_container.State.Running }}"
        gluetun_is_running: "{{ _gluetun_status.container.State.Running }}"
    - name: "Gluetun: print gluetun_is_running fact"
      ansible.builtin.debug:
        msg: "{{ gluetun_is_running }}"
    - name: Test vpn connection and generate fact
      community.docker.docker_container:
        docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
        name: gluetun-connection-test
        image: alpine:latest
        detach: false
        network_mode: container:gluetun
        entrypoint: sh
#       command: -c 'wget -qO- https://ipinfo.io'
        command: "-c \'wget -qO- {{ gluetun_ipinfo_url }}\'"
    - name: "Gluetun: Dump gluetun-connect-test log"
      ansible.builtin.command:
        cmd: /usr/local/bin/docker logs gluetun-connection-test
      become: true
      register: _gluetun_connection
      changed_when: false
    - name: "Gluetun: Set connection info fact"
      ansible.builtin.set_fact:
        gluetun_connection: "{{ _gluetun_connection }}"
    - name: "Gluetun: print gluetun_connection"
      ansible.builtin.debug:
        msg: "{{ _gluetun_connection }}"
  # End Block

# when: not _gluetun_state.exists
- name: "Gluetun: Restart the GlueTun VPN"
  when: _gluetun_state.exists
  block:
    - name: Restart GlueTun VPN Docker Container
      community.docker.docker_container:
        docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
        name: gluetun
#       image: qmcgaw/gluetun
        image: "qmcgaw/gluetun:{{ gluetun_container_version }}"
        networks:
          - name: synology-docker-network
        capabilities:
          - NET_ADMIN
        network_mode: bridge
        tty: true
        detach: true
        pull: true
        retries: 5
        delay: 30
        volumes:
          - "{{ container_directory_root }}/gluetun:/gluetun"
          - "/dev/net/tun:/dev/net/tun"
        env:
          VPN_SERVICE_PROVIDER: "{{ gluetun_vpn_service_provider }}"
          VPN_TYPE: "{{ gluetun_vpn_type }}"
          OPENVPN_USER: "{{ gluetun_openvpn_user }}"
          OPENVPN_PASSWORD: "{{ gluetun_openvpn_password }}"
          SERVER_REGIONS: "{{ gluetun_openvpn_regions }}"
          FIREWALL_OUTBOUND_SUBNETS: "{{ gluetun_firewall_outbound_subnets }}"
    #     PIA_ENCRYPTION: "normal"
    #     OPENVPN_CIPHER: "BF-CBC"
        ports:
          - "8888:8888/tcp"
          - "8388:8388/tcp"
          - "8388:8388/udp"
          # Deluge
          - "8112:8112"
          # NzbGet
          - "6789:6789"
          # NzbHydra2
          - "5076:5076"
          # Swag
          - "5080:80"
          - "5443:443"
          # Jackett
          - "9117:9117"
          # Bazarr
          - "6767:6767"
          # Sonarr
          - "8989:8989"
          # Radarr
          - "7878:7878"
          # Couchpotato
          - "5050:5050"
          # Mylar
          - "8090:8090"
          # Sabnzbd
          - "8080:8080"
          # Lidarr
          - "8686:8686"
          # Readarr
          - "8787:8787"
          # headphones
          - "8181:8181"
          # Prowlarr
          - "9696:9696"
          # Threadfin
          - "9981:9981"
          - "9982:9982"
          - "{{ gluetun_control_port }}:8000/tcp"
        restart: true
        restart_policy: always
        state: started
      register: _gluetun_status
    - name: "Gluetun: print gluetun status"
      ansible.builtin.debug:
        msg: "{{ _gluetun_status }}"
    - name: "Set gluetun_is_running fact"
      ansible.builtin.set_fact:
        gluetun_is_running: "{{ _gluetun_status.container.State.Running }}"
    - name: Test vpn connection and generate fact
      community.docker.docker_container:
        docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
        name: gluetun-connection-test
        image: alpine:latest
        detach: false
        network_mode: container:gluetun
        entrypoint: sh
#       command: -c 'wget -qO- https://ipinfo.io'
        command: "-c \'wget -qO- {{ gluetun_ipinfo_url }}\'"
    - name: "Gluetun: Dump gluetun-connect-test log (restart)"
      ansible.builtin.command:
        cmd: /usr/local/bin/docker logs gluetun-connection-test
      become: true
      register: _gluetun_connection
      changed_when: false
    - name: "Gluetun: Set connection info fact (restart)"
      ansible.builtin.set_fact:
        gluetun_connection: "{{ _gluetun_connection }}"
    - name: "Gluetun: print _gluetun_connection"
      ansible.builtin.debug:
        msg: "{{ _gluetun_connection }}"
# when: _gluetun_state.exists
  # End Block
- name: "Gluetun: show facts"
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
    - "gluetun_config_dir: {{ gluetun_config_dir }}"
    - "gluetun_state: {{ gluetun_state }}"
    - "gluetun_is_running: {{ gluetun_is_running }}"
    - "gluetun_connection: {{ gluetun_connection }}"
  tags:
    - gluetun
