galaxy_info:
  author: Peter J. Pouliot <peter@pouliot.net>
  description: Opinionated media stack deployment
  company:
  license: Apache-2.0
  min_ansible_version: 2.1
  galaxy_tags: []
dependencies: []
