---
# defaults file for emby
# Emby
emby_container_image: "ghcr.io/linuxserver/emby:latest"
emby_port: "8096"
user_puid: "1000"
group_pgid: "100"
default_timezone: "America/New_York"
container_directory_root: /volume1/docker
