---
# defaults file for jackett
jackett_container_image: "lscr.io/linuxserver/jackett:latest"
user_puid: "1000"
group_pgid: "100"
default_timezone: "America/New_York"
container_directory_root: /volume1/docker
