---
# defaults file for ergo
ergo_port: 6667
ergo_container_image: "ghcr.io/ergochat/ergo:stable"
user_puid: "1000"
group_pgid: "100"
default_timezone: "America/New_York"
container_directory_root: /volume1/docker
