---
user_puid: "1000"
group_pgid: "100"
default_timezone: "America/New_York"
container_directory_root: "/volume1/docker"

# This needs to be detected
# synology_docker_cli: "/usr/local/bin/docker"

cloudflared_container_image: "cloudflare/cloudflared:latest"
cloudflared_api_token: "{{ cloudflared_api_token }}"
atlantis_container_image: " ghcr.io/runatlantis/atlantis"

# Options for ansible-synology-dsm
#synology_dsm_api_configuration: true
synology_dsm_username: bwayne
#synology_dsm_password: P@ssW0rd
#synology_dsm_host: 10.1.1.36
#synology_dsm_nfs_enable: true
#synology_dsm_rsync_enable: true
#synology_dsm_user_home_service_enable: true

# Options for Synology tasks

#synology_default_user: administrator
sshkey_url: https://github.com/your_user.keys

# roles/synology/tasks/syno_packages.yml
synology_manage_packages: false
synology_package_list:
  - "ReplicationService"
  - "Virtualization"
  - "CMS"
# roles/synology/tasks/git.yml
synology_git_enable: true

# roles/synology/tasks/python.yml
synology_python_enable: true

# roles/synology/tasks/docker.yml
synology_docker_enable: true

# roles/synology/tasks/cloudflare_ddns.yml
synology_cloudflare_ddns_enable: true
