---
# Deluge
deluge_container_image: "lscr.io/linuxserver/deluge:latest"
deluge_port: 8112

user_puid: "1000"
group_pgid: "100"
default_timezone: "America/New_York"
container_directory_root: /volume1/docker

deluge_webapi_plugin_file: "WebAPI-0.4.0-py3.6.egg"
deluge_webapi_plugin_url: "https://github.com/idlesign/deluge-webapi/raw/master/dist/{{ deluge_webapi_plugin_file }}"
# Authentication
deluge_host_key: "ad98fe3c538842338b1ba3d3ae405941"
deluge_localclient_password: "aec5b4590a40bc36aebaf0836d0960788fc64028"
deluge_password_salt: c449b9c280d0f70d86046bf19d57078626e9e5b1
deluge_password_salted_sha1: 5ab406613a462ec3918ac711e0abb70ec851e4a6
deluge_password: deluge

# Locations
deluge_autoadd_location: "/downloads/torrents"
deluge_geoip_db_location: "/usr/share/GeoIP/GeoIP.dat"
deluge_download_location: "/downloads"
deluge_torrentfiles_location: "{{ deluge_download_location }}"
deluge_plugins_location: "/config/plugins"

# Configuration
deluge_move_completed: true
deluge_stop_seed_ratio: "1.0"
deluge_stop_seed_at_ratio: true
deluge_remove_seed_at_ratio: true
deluge_share_ratio_limit: "1.0"
deluge_dht: false
deluge_utpex: false
