---

- name: "Organizr: Create Organizr Directories"
  ansible.builtin.file:
    path: "{{ container_directory_root }}/organizr"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: "0775"
    recurse: true
  tags:
    - organizr
- name: "Organizr: Create Organizr container"
  community.docker.docker_container:
    docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
    name: organizr
    image: "{{ organizr_container_image }}"
    networks:
      - name: synology-docker-network
    pull: true
    retries: 5
    delay: 30
    network_mode: bridge
    volumes:
      - "{{ container_directory_root }}/organizr:/config:rw"
    env:
      PUID: "{{ user_puid }}"
      PGID: "{{ group_pgid }}"
      TZ: "{{ default_timezone }}"
    ports:
      - "{{ organizr_port }}:80"
    restart_policy: unless-stopped
    state: started
  tags:
    - organizr
# Threadfin Image Location
# https://github.com/Threadfin/Threadfin/raw/main/html/img/threadfin.png
# file must be put here: /volume1/docker/organizr/www/organizr/plugins/images/tabs#
