---

- name: Run Redis
  include_tasks: redis.yml
  when:
    - atlantis_redis_enable == true

- name: Run valkey
  include_tasks: valkey.yml
  when:
    - atlantis_valkey_enable == true


- name: Run Atlantis
  include_tasks: atlantis.yml

- name: Run Minio
  include_tasks: minio.yml
  when:
    - atlantis_minio_enable == true
