---
# vars file for swarm

swarm_manager_ips: "{{ groups.swarm| map('extract', hostvars)| selectattr('swarm_role', 'eq', 'manager')| map(attribute='ansible_host')|list|ansible.utils.ipaddr }}"
swarm_manager_names: "{{ groups.swarm| map('extract', hostvars)| selectattr('swarm_role', 'eq', 'manager')| map(attribute='inventory_hostname')|list }}"
swarm_manager_tokens: "{{ groups.swarm| map('extract', hostvars)| selectattr('swarm_role', 'eq', 'manager')| map(attribute='swarm_manager_token')|list }}"
swarm_worker_ips: "{{ groups.swarm| map('extract', hostvars)| selectattr('swarm_role', 'eq', 'worker')| map(attribute='ansible_host')|list }}"
swarm_worker_tokens: "{{ groups.swarm| map('extract', hostvars)| selectattr('swarm_role', 'eq', 'manager')| map(attribute='swarm_worker_token')|list }}"
swarm_network: "{{ groups.swarm| map('extract', hostvars,['ansible_default_ipv4','network'])|ansible.builtin.unique }}"
swarm_network_index: "{{ swarm_network | ansible.utils.index_of(test='equalto', value=ansible_default_ipv4.network) }}"
swarm_manager_index: "{{ swarm_manager_ips | ansible.utils.index_of(test='equalto', value=ansible_default_ipv4.address) }}"
local_swarm_network: "{{ swarm_network[swarm_network_index] }}"
local_swarm_manger: "{{ swarm_manager[swarm_manager_index] }}"
