---
- name: Prepare some local files to assit with synology platform automation
  block:
    - name: "Create directories /etc.defaults for ansible, opentofu and shared facts"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "root"
        group: "root"
        mode: "0755"
        recurse: true
      become: true
      with_items:
        - "/etc.defaults/ansible"
        - "/etc.defaults/interop.d/"
        - "/volume1/ansible/"
        # Create A directory for facts and artifacts between each.
        - "/etc.defaults/facts.d"
        # Create A directory for opentofu operations
        - "/etc.defaults/tofu.d"
        - "/volume1/tofu.d"
        - "/volume1/{{ ansible_facts.postal }}"
        - "/volume1/{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress | replace(':', '') }}"
      when:
        - ansible_facts.postal is defined
        - ansible_default_ipv4.macaddress is defined

# Steps
# Run ansible and generate hardcoded facts that are missing for synology when running ansible. based all the code from swarm.
# ansible.builtin.template
#  /etc/defaults/facts.d/ansible_distrobution.yml
#  /etc/defaults/facts.d/.ssh - for keys generated by
#  /etc/defaults/tofu.d/dns
#  /etc/defaults/tofu.d/dns/cname-from-ansible-location-fact-to-hostname/macaddress?
#  /etc/defaults/tofu.d/dns/lets-entcrypt-cert-wildcard-from-synology-hostname/macaddress?
#  /etc/defaults/tofu.d/dns/www1-github a records to github-pages endpoints from query with
# create a remote github repo at org/user for hostname
# configure github deploy keys  for hostname github repo at org/user for hostname
# repo could potententally be fork of uptime template
#  /etc/defaults/tofu.d/dns/www2-gitlab a records to gitlab-pages
# make changes to uptime along the way after testing urls to something exposed externally on unifi
# use tofu.d/github for create www server infra across github and gitlab putting dns in cloudlare for
# use tofu.d/github for control zone interoperable.systems
# cloudflare templates mailserver/webserver/letscrypt
# get to basic i'm alive with hostname resoution for every synology rumning docker and ssl wildcards off of base/hostname domain
