---
# roles/synology_swarm/tasks/worker_join.yml

- name: Join Swarm as a worker node
  community.docker.docker_swarm:
    state: join
    join_token: "{{ swarm_worker_token }}"
    remote_addrs: [ "{{ swarm_manager_ip }}:2377" ]
  when: "'inactive' in _swarm_status.stdout"
  register: _swarm_worker_join
  changed_when: "'New node is added to swarm cluster' in _swarm_worker_join.actions | default([])"
