---
# Flaresolverr
flaresolverr_container_image: "ghcr.io/flaresolverr/flaresolverr:latest"
flaresolverr_port: "8191"
user_puid: "1000"
group_pgid: "100"
default_timezone: "America/New_York"
container_directory_root: /volume1/docker
