---
# tasks file for ombi

- name: "Ombi: Create directories to house ombi data"
  ansible.builtin.file:
    path: "{{ container_directory_root }}/ombi"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: "0775"
    recurse: true
  tags:
    - ombi

- name: "Ombi: Create ombi container"
  community.docker.docker_container:
    docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
    name: ombi
    image: "{{ ombi_container_image }}"
    networks:
      - name: synology-docker-network
    pull: true
    retries: 5
    delay: 30
    volumes:
      - "{{ container_directory_root }}/ombi:/config"
    ports:
      - "{{ ombi_exposed_port }}:3579"
    env:
      PUID: "{{ user_puid }}"
      PGID: "{{ group_pgid }}"
      TZ: "{{ default_timezone }}"
      UMASK: "022"
    state: started
    restart_policy: unless-stopped
  tags:
    - ombi
