galaxy_info:
  role_name: pihole
  namespace: ppouliot
  author: Peter J. Pouliot <peter@pouliot.net>
  description: Opinionated pihole container deployment
  company:
  license: Apache-2.0
  min_ansible_version: 2.1
  platforms:
    - name: synology
      version:
        - any
  galaxy_tags: []
dependencies: []
