---

- name: "Create directories to house couchpotato data"
  file:
    path: "{{ container_directory_root }}/couchpotato"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: 0775
    recurse: true

- name: Create couchpotato container
  community.docker.docker_container:
    docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
    name: couchpotato
    image: "{{ couchpotato_container_image }}"
    networks:
      - name: synology-docker-network
    pull: true
    retries: 5
    delay: 30
    network_mode: container:gluetun
#   network_mode: host
#   ports:
#     - "5050:5050"
    volumes:
      - "{{ container_directory_root }}/couchpotato:/config"
      - "{{ container_directory_root }}/downloads:/downloads"
      - "{{ container_directory_root }}/movies:/movies"
    env:
      PUID: "{{ user_puid }}"
      PGID: "{{ group_pgid }}"
      TZ: "{{ default_timezone }}"
      UMASK_SET: "022"
    restart_policy: unless-stopped
