---
# tasks file for plex

- name: "Plex: Check if ssdp service is running"
  ansible.builtin.command:
    cmd: /usr/syno/bin/synosystemctl get-active-status ssdp
  register: synology_ssdp_service_status
  ignore_errors: true
  failed_when: synology_ssdp_service_status.rc != 0 or synology_ssdp_service_status.rc != 3
  changed_when: false
  tags:
    - plex

- name: "Plex: Show ssdp service status"
  ansible.builtin.debug:
    var: synology_ssdp_service_status.stdout_lines[0]
  tags:
    - plex

- name: "Plex: Disable ssdp service if enabled"
  ansible.builtin.command:
    cmd: /usr/syno/bin/synosystemctl disable ssdp
  when: synology_ssdp_service_status.stdout_lines[0] == "Service [ssdp] status=[enable]"
  changed_when: true
  tags:
    - plex

- name: "Plex: Create directories to house plex config and transcode data"
  ansible.builtin.file:
    path: "{{ container_directory_root }}/plex"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: "0775"
    recurse: yes
  tags:
    - plex

- name: "Plex: Create plex/transcode directory for transcode data"
  ansible.builtin.file:
    path: "{{ container_directory_root }}/plex/transcode"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: "0775"
    recurse: yes
  tags:
    - plex

- name: "Plex: Run plex container"
  block:
    - name: "Plex: Run plex container"
      community.docker.docker_container:
        docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
        name: plex
        image: "{{ plex_container_image }}"
        network_mode: host
        pull: yes
        privileged: yes
        devices:
          - /dev/dri:/dev/dri
        volumes:
          - "{{ container_directory_root }}/plex:/config"
          - "{{ container_directory_root }}/plex/transcode:/transcode"
          - "{{ container_directory_root }}/tv:/data/tv"
          - "{{ container_directory_root }}/movies:/data/movies"
          - "{{ container_directory_root }}/music:/data/music"
        env:
          PLEX_UID: "{{ user_puid }}"
          PLEX_GID: "{{ group_pgid }}"
          TZ: "{{ default_timezone }}"
          PLEX_CLAIM: "{{ plex_claim_token }}"
          ADVERTISE_IP: "http://{{ ansible_default_ipv4.address }}:32400"
        restart_policy: unless-stopped
        state: started
  tags:
    - plex
  # End Block
