---
- name: "Create directories to house htpcmanager data"
  file:
    path: "{{ container_directory_root }}/htpcmanager"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: 0775
    recurse: true
- name: Create htpcmanager container
  community.docker.docker_container:
    docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
    name: htpcmanager
    image: "{{ htpcmanager_container_image }}"
    networks:
      - name: synology-docker-network
    pull: true
    retries: 5
    delay: 30
    volumes:
      - "{{ container_directory_root }}/htpcmanager:/config"
    ports:
      - 8085:8085
    env:
      PUID: "{{ user_puid }}"
      PGID: "{{ group_pgid }}"
      TZ: "{{ default_timezone }}"
      UMASK: "022"
    state: started
    restart_policy: unless-stopped
