---
# tasks file for imagemaid

- name: "Imagemaid: Create directories to house imagemaid config data"
  ansible.builtin.file:
    path: "{{ container_directory_root }}/imagemaid"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: "0775"
    recurse: yes

- name: "Imagemaid: Create imagemaid/config directory"
  ansible.builtin.file:
    path: "{{ container_directory_root }}/imagemaid/config"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: "0775"
    recurse: yes

- name: "Imagemaid: Create imagemaid/config/assets directory"
  ansible.builtin.file:
    path: "{{ container_directory_root }}/imagemaid/config/assets"
    state: directory
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: "0775"

- name: "Imagemaid: Deploy imagemaid config file"
  ansible.builtin.template:
    src: "config.yml.j2"
    dest: "{{ container_directory_root }}/imagemaid/config/config.yml"
    owner: "{{ user_puid }}"
    group: "{{ group_pgid }}"
    mode: "0600"
  register: imagemaid_config

- name: "Imagemaid: Run imagemaid container"
  block:
    - name: "Imagemaid: Run imagemaid container"
      community.docker.docker_container:
        docker_host: tcp://{{ ansible_default_ipv4.address }}:2375
        name: imagemaid
        image: "{{ imagemaid_container_image }}"
        pull: yes
        command: "tini -s python3 imagemaid.py --"
        volumes:
          - "{{ container_directory_root }}/imagemaid/config:/config:rw"
          - "{{ container_directory_root }}/plex:/plex:rw"
        env:
          PLEX_META_MANAGER_UID: "{{ user_puid }}"
          PLEX_META_MANAGER_GID: "{{ group_pgid }}"
          TZ: "{{ default_timezone }}"
          PLEX_CLAIM: "{{ plex_claim_token }}"
          ADVERTISE_IP: "http://{{ ansible_default_ipv4.address }}:32400"
          PMM_DOCKER: "true"
        restart_policy: unless-stopped
        state: started
  # End Block
